
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace MLModel1_ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
            {
                Data_as_of = @"11/17/2021",
                Start_Date = @"01/01/2020",
                End_Date = @"11/13/2021",
                Sex = @"Female",
                Age_Years = @"<1 Year",
                Total_deaths = 15827F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = MLModel1.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual COVID_19_Deaths with predicted COVID_19_Deaths from sample data...\n\n");


            Console.WriteLine($"Data_as_of: {@"11/17/2021"}");
            Console.WriteLine($"Start_Date: {@"01/01/2020"}");
            Console.WriteLine($"End_Date: {@"11/13/2021"}");
            Console.WriteLine($"Sex: {@"Female"}");
            Console.WriteLine($"Age_Years: {@"<1 Year"}");
            Console.WriteLine($"Total_deaths: {15827F}");
            Console.WriteLine($"COVID_19_Deaths: {69F}");


            Console.WriteLine($"\n\nPredicted COVID_19_Deaths: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
